name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  file_paths:
    description: 'Urls to compare'
    required: true
    default: 'db-urls/qa-1.json'
  base_url:
    description: 'Base URL for comparison'
    required: true
  github_token:
    description: 'Git Token'
    required: true
  percy_token:
    description: 'Percy Token'
    required: true
  public_builder_api_key:
    description: 'Builder API'
    required: true

runs:
  using: node20
  main: dist/index.js
